### ISSUE TITLE
volume path issue

### ISSUE THREAD

**Issue by tongzh** [rezzza/docker-moco#5]
There might be a typo in volume folder path, actually the running command should be:
```
$ docker run -v /my/own/moco-directory:/var/moco -p 8000:8000 rezzza/docker-moco:latest
```

**Comment by tyx** [comment]
You're right !

**Comment by tyx** [comment]
Fixed in https://github.com/rezzza/docker-moco/commit/1e3123b29c288bec7e044de028f7694e5aaeee50
